version: "3.8"

services:
  backend:
    image: python:3.10-slim
    container_name: farm-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - redis
    networks:
      - farm-network

  frontend:
    image: node:16-alpine
    container_name: farm-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    command: >
      sh -c "npm install chart.js react-chartjs-2 web-vitals &&
             npm start"
    depends_on:
      - backend
    networks:
      - farm-network

  redis:
    image: redis:alpine
    container_name: farm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - farm-network

networks:
  farm-network:
    driver: bridge

volumes:
  redis_data:
